/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as MiNegocioRouteImport } from './routes/mi-negocio'
import { Route as ConversacionesRouteImport } from './routes/conversaciones'
import { Route as ClientesRouteImport } from './routes/clientes'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const MiNegocioRoute = MiNegocioRouteImport.update({
  id: '/mi-negocio',
  path: '/mi-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversacionesRoute = ConversacionesRouteImport.update({
  id: '/conversaciones',
  path: '/conversaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/clientes': typeof ClientesRoute
  '/conversaciones': typeof ConversacionesRoute
  '/mi-negocio': typeof MiNegocioRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesByTo {
  '/clientes': typeof ClientesRoute
  '/conversaciones': typeof ConversacionesRoute
  '/mi-negocio': typeof MiNegocioRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/clientes': typeof ClientesRoute
  '/conversaciones': typeof ConversacionesRoute
  '/mi-negocio': typeof MiNegocioRoute
  '/productos': typeof ProductosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/clientes' | '/conversaciones' | '/mi-negocio' | '/productos'
  fileRoutesByTo: FileRoutesByTo
  to: '/clientes' | '/conversaciones' | '/mi-negocio' | '/productos'
  id:
    | '__root__'
    | '/clientes'
    | '/conversaciones'
    | '/mi-negocio'
    | '/productos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClientesRoute: typeof ClientesRoute
  ConversacionesRoute: typeof ConversacionesRoute
  MiNegocioRoute: typeof MiNegocioRoute
  ProductosRoute: typeof ProductosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-negocio': {
      id: '/mi-negocio'
      path: '/mi-negocio'
      fullPath: '/mi-negocio'
      preLoaderRoute: typeof MiNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversaciones': {
      id: '/conversaciones'
      path: '/conversaciones'
      fullPath: '/conversaciones'
      preLoaderRoute: typeof ConversacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ClientesRoute: ClientesRoute,
  ConversacionesRoute: ConversacionesRoute,
  MiNegocioRoute: MiNegocioRoute,
  ProductosRoute: ProductosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
