/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as MiNegocioRouteImport } from './routes/mi-negocio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversacionesRouteImport } from './routes/conversaciones'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const MiNegocioRoute = MiNegocioRouteImport.update({
  id: '/mi-negocio',
  path: '/mi-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversacionesRoute = ConversacionesRouteImport.update({
  id: '/conversaciones',
  path: '/conversaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clientes': typeof ClientesRoute
  '/conversaciones': typeof ConversacionesRoute
  '/dashboard': typeof DashboardRoute
  '/mi-negocio': typeof MiNegocioRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clientes': typeof ClientesRoute
  '/conversaciones': typeof ConversacionesRoute
  '/dashboard': typeof DashboardRoute
  '/mi-negocio': typeof MiNegocioRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clientes': typeof ClientesRoute
  '/conversaciones': typeof ConversacionesRoute
  '/dashboard': typeof DashboardRoute
  '/mi-negocio': typeof MiNegocioRoute
  '/productos': typeof ProductosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clientes'
    | '/conversaciones'
    | '/dashboard'
    | '/mi-negocio'
    | '/productos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clientes'
    | '/conversaciones'
    | '/dashboard'
    | '/mi-negocio'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clientes'
    | '/conversaciones'
    | '/dashboard'
    | '/mi-negocio'
    | '/productos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClientesRoute: typeof ClientesRoute
  ConversacionesRoute: typeof ConversacionesRoute
  DashboardRoute: typeof DashboardRoute
  MiNegocioRoute: typeof MiNegocioRoute
  ProductosRoute: typeof ProductosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-negocio': {
      id: '/mi-negocio'
      path: '/mi-negocio'
      fullPath: '/mi-negocio'
      preLoaderRoute: typeof MiNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversaciones': {
      id: '/conversaciones'
      path: '/conversaciones'
      fullPath: '/conversaciones'
      preLoaderRoute: typeof ConversacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClientesRoute: ClientesRoute,
  ConversacionesRoute: ConversacionesRoute,
  DashboardRoute: DashboardRoute,
  MiNegocioRoute: MiNegocioRoute,
  ProductosRoute: ProductosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
